version: '3'
services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: test-node-task-api
    restart: unless-stopped
    ports:
    - "3333:3333"
    networks:
    - api-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: test-node-task-db
    restart: unless-stopped
    tty: true
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: tasks
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - dbdata:/var/lib/mysql
    networks:
    - api-network

  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    container_name: test-node-task-angular
    restart: unless-stopped
    ports:
    - "3000:80"

#Docker Networks
networks:
  api-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local